### PR TITLE
Add new question to beginner js

### PR DESCRIPTION
**Pull request by SamSaias**

### CODE REVIEW

**Comment by the-real-i9** [comment]
At the `explanation` why not say, the `unshift()` method of an array, adds one or more elements to the beginning of an array. Or should I approve it and do the corrections?

**Comment by the-real-i9** [comment]
At the `option` property , wrap each new Array inside the double quotes in square brackets [], like this "['cup', 2, 'fumble']"  *so it won't look like it just returns a string of comma separated list*, also for the `correctAnswer`

**Comment by the-real-i9** [comment]
At the `reference`, I guess by mistake you wrapped the link address in double quotes '\[linkText](~~"linkAddress"~~)', the syntax should be '\[linkText](linkAddress)'

**Comment by SamSaias** [comment]
Thank you for all the feedback, I will make the requested changes.

**Review by the-real-i9 — APPROVED** [review]
Thanks for contributing, we hope to see more of your contributions, tell the world.

**Pull request merged**
