### PR TITLE
fixed some typos and added an intermediate javascript question

### PR DESCRIPTION
**Pull request by IcedTeaTech**
Nothing too fancy, just figuring out how to contribute. First time I work on an open-source project.

### CODE REVIEW

**Comment by the-real-i9** [comment]
Ok... We've discussed somewhere else... Fix the issues

**Comment by IcedTeaTech** [comment]
I see that I can just push new changes and it will update here as well. Learning so much today.

**Comment by the-real-i9** [comment]
I saw a \n you won't need that, there was no problem with that

**Comment by IcedTeaTech** [comment]
I know, but I do think it looks cleaner. I can remove it if you want though.

**Comment by the-real-i9** [comment]
I think in a template string, you won't need a \n, the empty line you used initially will work perfectly, just like in a real code

**Comment by the-real-i9** [comment]
I just tried it, template string will display your \n

**Comment by IcedTeaTech** [comment]
image
When I leave out the \n it displays like this.

**Comment by IcedTeaTech** [comment]
That indentation is just a spacing issue. Still when leaving out the \n I don't get an empty line between the two.

**Comment by the-real-i9** [comment]
You can have it like this
```
let myAge = 23;
// This empty line should work fine in the code
function printAge() {

} 
```

**Comment by the-real-i9** [comment]
Oh! add \n and let me see the result

**Comment by IcedTeaTech** [comment]
image
This is the result when I keep the \n

**Review by the-real-i9 — APPROVED** [review]
I'm sorry you were right! If you can help on the Contributing.md. At the Step(x) `code property` section, add that:
> One can use escape characters with backslashes.

**Pull request merged**
