### PR TITLE
edited answer and explanation for question

### PR DESCRIPTION
**Pull request by IcedTeaTech**
After discussion, found out that the first answer was not correct.

### CODE REVIEW

**Comment by the-real-i9** [comment]
You said "a function declared like this", why not say, a function declaration. Since that's the name of that kind of function. An intermediate developer should know what a function declaration is, different from a function expression

**Comment by the-real-i9** [comment]
And also, I think you wanted to say "It cannot be used until it is initialized". Rather than "...until it is declared"

**Comment by the-real-i9** [comment]
Also remember to change your reference... Since that was the reference for the previous wrong one

**Comment by IcedTeaTech** [comment]
Edited the explanation text and got rid of the "like this" part. However, the piece about initialization/declaration I took off of the resources website (check picture) so it should be correct, W3 Schools is a valid source. 

image

Reference stays the same as it's the same article people can use to look into the matter.

**Comment by the-real-i9** [comment]
Ok. then

**Review by the-real-i9 — APPROVED** [review]
Approved and merged

**Pull request merged**
